name: Check style and code formatting and tests for maven app
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'oracle'
          java-version: '21'

      - name: Verify Spotless Formatting
        run: mvn spotless:check

      - name: Run Checkstyle
        run: mvn checkstyle:check

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: petstore-backend
          path: '${{ github.workspace }}/target/*.jar'

      - name: Run Tests
        run: mvn test


